export const MENU_EVENT_KEY_PROFILE = 'MENU_EVENT_KEY_PROFILE';
export const MENU_EVENT_KEY_ACCOUNT = 'MENU_EVENT_KEY_ACCOUNT';
export const MENU_EVENT_KEY_LOGOUT = 'MENU_EVENT_KEY_LOGOUT';
export const VIEW_HIKES = 'VIEW_HIKES';
export const VIEW_HIKE = 'VIEW_HIKE';
export const VIEW_GEAR = 'VIEW_GEAR';
export const VIEW_FOOD = 'VIEW_FOOD';
